# Generated by Django 5.2.14 on 2026-05-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ministries", "0002_ministry_delete_ministerio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("document", models.CharField(max_length=50, unique=True)),
                ("pin", models.CharField(max_length=255)),
                ("fingerprint", models.CharField(max_length=255)),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServerMinistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joinedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ministries.ministry",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="servers.server"
                    ),
                ),
            ],
            options={
                "unique_together": {("server", "ministry")},
            },
        ),
        migrations.AddField(
            model_name="server",
            name="ministries",
            field=models.ManyToManyField(
                related_name="servers",
                through="servers.ServerMinistry",
                to="ministries.ministry",
            ),
        ),
    ]
