# Generated by Django 5.2.14 on 2026-05-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="document",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
