# Generated by Django 5.2.14 on 2026-05-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_alter_server_document_alter_server_fingerprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverministry",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_ministries",
                to="servers.server",
            ),
        ),
    ]
