# Generated by Django 5.2.14 on 2026-05-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("ministries", "0002_ministry_delete_ministerio"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("startTime", models.TimeField()),
                ("endTime", models.TimeField()),
                ("isActive", models.BooleanField(default=True)),
                (
                    "eventType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="events.eventtype",
                    ),
                ),
                (
                    "leaderMinistry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leader_recurring_events",
                        to="ministries.ministry",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="events.eventstatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringEventMinistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ministries.ministry",
                    ),
                ),
                (
                    "recurringEvent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.recurringevent",
                    ),
                ),
            ],
            options={
                "unique_together": {("recurringEvent", "ministry")},
            },
        ),
        migrations.AddField(
            model_name="recurringevent",
            name="ministries",
            field=models.ManyToManyField(
                related_name="recurring_events",
                through="events.RecurringEventMinistry",
                to="ministries.ministry",
            ),
        ),
    ]
