# Generated by Django 5.2.14 on 2026-06-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_recurringevent_recurringeventministry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
