# Generated by Django 5.2.14 on 2026-07-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_eventtype_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="code",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
