# Generated by Django 5.2.14 on 2026-07-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_eventtype_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
    ]
