# Generated by Django 5.2.14 on 2026-07-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_isactive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventstatus",
            name="code",
        ),
        migrations.RemoveField(
            model_name="eventstatus",
            name="order",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="code",
        ),
    ]
