# Generated by Django 5.2.14 on 2026-07-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_eventstatus_code_remove_eventstatus_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="isActive",
        ),
    ]
