# Generated by Django 5.2.14 on 2026-07-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_event_isactive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringevent",
            name="ministries",
        ),
        migrations.RemoveField(
            model_name="recurringevent",
            name="leaderMinistry",
        ),
        migrations.DeleteModel(
            name="RecurringEventMinistry",
        ),
    ]
