# Generated by Django 5.2.13 on 2026-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_recurringevent_ministries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
