# Generated by Django 5.2.13 on 2026-07-14 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_seed_event_statuses'),
        ('ministries', '0002_ministry_delete_ministerio'),
        ('servers', '0003_alter_serverministry_server'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('assignedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.event')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministries.ministry')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='servers.server')),
            ],
            options={
                'unique_together': {('event', 'server')},
            },
        ),
    ]
