# Generated by Django 5.2.13 on 2026-07-14 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_seed_cancelado_status'),
        ('ministries', '0002_ministry_delete_ministerio'),
        ('servers', '0003_alter_serverministry_server'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ATTENDANCE_REGISTERED', 'Registro de asistencia'), ('RECONCILIATION_EXECUTED', 'Reconciliación ejecutada'), ('RECONCILIATION_REPLACEMENT', 'Reemplazo registrado')], max_length=50)),
                ('table', models.CharField(max_length=50)),
                ('recordId', models.IntegerField()),
                ('performedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previousHash', models.CharField(blank=True, max_length=128, null=True)),
                ('currentHash', models.CharField(editable=False, max_length=128)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KioskoAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosko_attempts', to='servers.server')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executedAt', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='events.event')),
                ('executedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event',)},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('integrityHash', models.CharField(editable=False, max_length=128)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministries.ministry')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='servers.server')),
            ],
            options={
                'unique_together': {('server', 'event')},
            },
        ),
        migrations.CreateModel(
            name='ReconciliationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('ASSIGNED', 'Asistió (asignado)'), ('VOLUNTEER', 'Voluntario'), ('ABSENT', 'Ausente'), ('REPLACEMENT', 'Reemplazó')], max_length=20)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='events.reconciliation')),
                ('replacedServer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='servers.server')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_details', to='servers.server')),
            ],
            options={
                'unique_together': {('reconciliation', 'server')},
            },
        ),
    ]
