# Generated by Django 6.0.7 on 2026-07-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_attendance_checkouttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationdetail',
            name='classification',
            field=models.CharField(choices=[('ASSIGNED', 'Asistió (asignado)'), ('VOLUNTEER', 'Voluntario'), ('ABSENT', 'Ausente'), ('INCOMPLETE', 'Ingresó sin registrar salida'), ('REPLACEMENT', 'Reemplazó')], max_length=20),
        ),
    ]
